import {
    //Sun,
    WiDayCloudy,
    WiFog,
    WiRain,
    WiSnowWind,
    WiSleet,
    WiDayThunderstorm,
    WiDaySnowThunderstorm
} from 'react-icons/wi';

import {
    CloudFog,
    CloudSun,
    Cloud,
    Sun,
    CloudRain,
    CloudSnow,
    CloudLightning,
    CloudRainWind,
    Droplet,
    Wind,
    ThermometerSun,
    ThermometerSnowflake,
    HelpCircle,
    SnowflakeIcon
} from "lucide-react";


const WeatherIconsReformatted = [
    { code: 1000, text: "Sunny", IconComponent: Sun },
    { code: 1003, text: "Partly cloudy", IconComponent: CloudSun },
    { code: 1006, text: "Cloudy", IconComponent: Sun },
    { code: 1009, text: "Overcast", IconComponent: CloudFog },
    { code: 1030, text: "Mist", IconComponent: CloudFog },
    { code: 1063, text: "Patchy rain possible", IconComponent: CloudRain },
    { code: 1066, text: "Patchy snow possible", IconComponent: CloudRainWind },
    { code: 1069, text: "Patchy sleet possible", IconComponent: Droplet },
    { code: 1072, text: "Patchy freezing drizzle possible", IconComponent: Droplet },
    { code: 1087, text: "Thundery outbreaks possible", IconComponent: CloudLightning },
    { code: 1114, text: "Blowing snow", IconComponent: CloudRainWind },
    { code: 1117, text: "Blizzard", IconComponent: CloudRainWind },
    { code: 1200, text: "Fog", IconComponent: CloudFog },
    { code: 1147, text: "Freezing fog", IconComponent: CloudFog },
    { code: 1153, text: "Light drizzle", IconComponent: CloudRain },
    { code: 1168, text: "Freezing drizzle", IconComponent: CloudRain },
    { code: 1171, text: "Heavy freezing drizzle", IconComponent: CloudRain },
    { code: 1183, text: "Light rain", IconComponent: CloudRain },
    { code: 1186, text: "Moderate rain at times", IconComponent: CloudRain },
    { code: 1189, text: "Moderate rain", IconComponent: CloudRain },
    { code: 1192, text: "Heavy rain at times", IconComponent: CloudRain },
    { code: 1195, text: "Heavy rain", IconComponent: CloudRain },
    { code: 1198, text: "Light freezing rain", IconComponent: CloudRain },
    { code: 1200, text: "Patchy light drizzle", IconComponent: CloudRain },
    { code: 11200, text: "Patchy light rain", IconComponent: CloudRain },
    { code: 2001, text: "Moderate or heavy freezing rain", IconComponent: CloudRain },
    { code: 2004, text: "Light sleet", IconComponent: Droplet },
    { code: 2007, text: "Moderate or heavy sleet", IconComponent: Droplet },
    { code: 1210, text: "Patchy light snow", IconComponent: CloudRainWind },
    { code: 1213, text: "Light snow", IconComponent: CloudRainWind },
    { code: 1216, text: "Patchy moderate snow", IconComponent: CloudRainWind },
    { code: 1219, text: "Moderate snow", IconComponent: CloudRainWind },
    { code: 1222, text: "Patchy heavy snow", IconComponent: CloudRainWind },
    { code: 1225, text: "Heavy snow", IconComponent: CloudRainWind },
    { code: 1237, text: "Ice pellets", IconComponent: CloudRainWind },
    { code: 1240, text: "Light rain shower", IconComponent: CloudRain },
    { code: 1243, text: "Moderate or heavy rain shower", IconComponent: CloudRain },
    { code: 1246, text: "Torrential rain shower", IconComponent: CloudRain },
    { code: 1249, text: "Light sleet showers", IconComponent: WiSleet },
    { code: 1252, text: "Moderate or heavy sleet showers", IconComponent: SnowflakeIcon },
    { code: 1255, text: "Light snow showers", IconComponent: CloudRainWind },
    { code: 1258, text: "Moderate or heavy snow showers", IconComponent: CloudRainWind },
    { code: 1261, text: "Light showers of ice pellets", IconComponent: Droplet },
    { code: 1264, text: "Moderate or heavy showers of ice pellets", IconComponent: CloudRainWind },
    { code: 1273, text: "Patchy light rain with thunder", IconComponent: CloudLightning },
    { code: 1276, text: "Moderate or heavy rain with thunder", IconComponent: CloudLightning },
    { code: 1279, text: "Patchy light snow with thunder", IconComponent: CloudLightning },
    { code: 1282, text: "Moderate or heavy snow with thunder", IconComponent: CloudLightning },
];

export { WeatherIconsReformatted };
